---
- name: Install and configure Grafana Alloy
  hosts: all
  become: true
  vars:
    alloy_repo_url: "https://rpm.grafana.com"
    alloy_gpg_key_url: "https://rpm.grafana.com/gpg.key"
    alloy_repo_file: "/etc/yum.repos.d/grafana.repo"
    alloy_config_dir: "/etc/alloy"
    alloy_config_file: "config.alloy"
    alloy_service_file: "/etc/systemd/system/alloy.service"
    alloy_data_dir: "/var/lib/alloy/data"
    alloy_listen_port: 12345

  tasks:
    - name: Ensure required packages are present
      ansible.builtin.package:
        name:
          - wget
          - firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Import Grafana GPG key
      ansible.builtin.get_url:
        url: "{{ alloy_gpg_key_url }}"
        dest: "/tmp/grafana.gpg.key"

    - name: Import GPG key into RPM
      ansible.builtin.rpm_key:
        state: present
        key: "/tmp/grafana.gpg.key"

    - name: Add Grafana Alloy repository
      ansible.builtin.copy:
        dest: "{{ alloy_repo_file }}"
        content: |
          [grafana]
          name=grafana
          baseurl={{ alloy_repo_url }}
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey={{ alloy_gpg_key_url }}
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        mode: '0644'

    - name: Install Grafana Alloy
      ansible.builtin.package:
        name: alloy
        state: present

    - name: Ensure Alloy config directory exists
      ansible.builtin.file:
        path: "{{ alloy_config_dir }}"
        state: directory
        owner: alloy
        group: alloy
        mode: '0755'

    - name: Copy Alloy configuration file
      ansible.builtin.copy:
        src: "files/{{ alloy_config_file }}"
        dest: "{{ alloy_config_dir }}/{{ alloy_config_file }}"
        owner: alloy
        group: alloy
        mode: '0644'

    - name: Ensure Alloy data directory exists
      ansible.builtin.file:
        path: "{{ alloy_data_dir }}"
        state: directory
        owner: alloy
        group: alloy
        mode: '0755'

    - name: Create systemd service for Alloy
      ansible.builtin.copy:
        dest: "{{ alloy_service_file }}"
        content: |
          [Unit]
          Description=Grafana Alloy
          After=network.target

          [Service]
          User=alloy
          Group=alloy
          ExecStart=/usr/bin/alloy run --server.http.listen-addr=0.0.0.0:{{ alloy_listen_port }} --storage.path={{ alloy_data_dir }} {{ alloy_config_dir }}/{{ alloy_config_file }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd and start Alloy service
      ansible.builtin.systemd:
        daemon_reload: true
        name: alloy
        enabled: true
        state: restarted

    - name: Allow Alloy port through firewalld
      ansible.posix.firewalld:
        port: "{{ alloy_listen_port }}/tcp"
        permanent: true
        state: enabled
        immediate: yes
