version: "3.9"

networks:
  monitoring:
    driver: bridge

services:
  checkmk:
    image: docker.io/checkmk/check-mk-raw:2.2.0p41
    container_name: checkmk
    ports:
      - "5000:5000"
    environment:
      - CMK_SITE_ID=cmk
    volumes:
      - /home/scmx/containers/checkmk/sites:/omd/sites
    cap_add:
      - NET_RAW  # Required for ICMP ping checks
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=tribe-29-checkmk-datasource
    volumes:
      - /home/scmx/containers/grafana/grafana_data:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9091"
    command: --config.file=/etc/prometheus/prometheus.yml --web.listen-address=:9091 --web.enable-admin-api
    volumes:
      - /home/scmx/containers/prometheus/prometheus_data:/prometheus
      - /home/scmx/containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - /home/scmx/containers/loki/loki_data:/loki
      - /home/scmx/containers/loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - /home/scmx/containers/promtail/log:/var/log
      - /home/scmx/containers/promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - monitoring

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - '9130:9130'
    environment:
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
      - UP_PROMETHEUS_NAMESPACE=unpoller
      - UP_INFLUXDB_DISABLE=true
      - UP_POLLER_DEBUG=true
      - UP_UNIFI_CONTROLLER_0_URL=https://10.0.0.1
      - UP_UNIFI_CONTROLLER_0_USER=unifipoller
      - UP_UNIFI_CONTROLLER_0_PASS=password
      - UP_UNIFI_CONTROLLER_0_SITE=default
      - UP_UNIFI_CONTROLLER_0_IS_UNIFI_OS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=true
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=true
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=true
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - /home/scmx/containers/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      - TZ=America/New_York
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
    - monitoring